sharding:
  jdbc:
    datasource:
      names: ds
      ds:
         type: org.apache.commons.dbcp.BasicDataSource
         driver-class-name: com.mysql.jdbc.Driver
         url: jdbc:mysql://13.58.107.166:3306/pay?useUnicode=true&characterEncoding=utf-8&useSSL=true
         username: root
         password: tangJ#8x2@3434343x
    config:
        tables:
          t_order:
            actual-data-nodes: ds.t_order_${0..1}
            table-strategy:
              inline:
                sharding-column: order_id
                algorithm-expression: t_order_${order_id % 2}
            key-generator-column-name: order_id
          t_order_item:
            actual-data-nodes: ds.t_order_item_${0..1}
            table-strategy:
              inline:
                sharding-column: order_id
                algorithm-expression: t_order_item_${order_id % 2}
            key-generator-column-name: order_item_id